let
    Origen = Csv.Document(File.Contents("C:\Users\Computer\Documents\SEE_UsandoBasesDeDatosDeMasDeUnMillonDeFilasConExcelYPowerPivot\Proyecto_PowerPivot\DATOS_ABIERTOS_ENCUESTA_CENSO_2010\cenec_2010.csv"),[Delimiter=";", Columns=114, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"s1p2", Int64.Type}, {"s1p3", Int64.Type}, {"s2p4_1", Int64.Type}, {"s2p5", Int64.Type}, {"s2p6", Int64.Type}, {"s2p7", Int64.Type}, {"s2p8", Int64.Type}, {"s2p9", Int64.Type}, {"s3p1_1c2", Int64.Type}, {"s3p1_1c3", Int64.Type}, {"s3p1_1c1", Int64.Type}, {"s3p1_2c2", Int64.Type}, {"s3p1_2c3", Int64.Type}, {"s3p1_2c1", Int64.Type}, {"s3p1_3c1", Int64.Type}, {"s3p1_3c2", Int64.Type}, {"s3p1_3c3", Int64.Type}, {"s4p4c2", Int64.Type}, {"s4p6", Int64.Type}, {"s4p7c1", Int64.Type}, {"s4p7c2", Int64.Type}, {"s4p7c3", Int64.Type}, {"s4p7c4", Int64.Type}, {"s5p1", Int64.Type}, {"s5p6_1c1", Int64.Type}, {"s5p6_1c2", Int64.Type}, {"s5p6_2c1", Int64.Type}, {"s5p6_2c2", Int64.Type}, {"s5p6_3c1", Int64.Type}, {"s5p6_3c2", Int64.Type}, {"s5p6_4c1", Int64.Type}, {"s5p6_4c2", Int64.Type}, {"s5p7_1c1", Int64.Type}, {"s5p7_2c1", Int64.Type}, {"s5p7_3c1", Int64.Type}, {"s5p7_4c1", Int64.Type}, {"s5p7_4c2", Int64.Type}, {"s6p1", type text}, {"s6p2", type text}, {"s6p3", type text}, {"s6p3_1", type text}, {"s6p4_1_1", type text}, {"s6p4_1_2", type text}, {"s6p4_2", type text}, {"s6p4_3", type text}, {"s6p4_4_1", type text}, {"s6p4_4_2", type text}, {"z6p4_1_1", type text}, {"z6p4_1_2", type text}, {"z6p4_2", type text}, {"z6p4_3", type text}, {"z6p4_4_1", type text}, {"z6p4_4_2", type text}, {"s6p5", type text}, {"s6p5_1", type text}, {"s6p6", type text}, {"s6p8", type text}, {"s6p8_1", type text}, {"s6p9", type text}, {"s6p9_1", type text}, {"s6p10", type text}, {"s6p10_1", type text}, {"s6p11", type text}, {"s6p12", type text}, {"s9_p1", type text}, {"ciiu4_p", Int64.Type}, {"ciiu4_s", Int64.Type}, {"ciiu2.P", type text}, {"ciiu3.P", type text}, {"ciiu4.P", type text}, {"ciiu2.S", type text}, {"ciiu3.S", type text}, {"ciiu4.S", type text}, {"cpc_pe2d", Int64.Type}, {"cpc_pe3d", Int64.Type}, {"cpc_pe4d", Int64.Type}, {"cpc_pc2d", Int64.Type}, {"cpc_pc3d", Int64.Type}, {"cpc_pc4d", Int64.Type}, {"cpc_so2d", Int64.Type}, {"cpc_so3d", Int64.Type}, {"cpc_so4d", Int64.Type}, {"cpc_mp2d", Int64.Type}, {"cpc_mp3d", Int64.Type}, {"cpc_mp4d", Int64.Type}, {"rgnatu", Int64.Type}, {"cant", Int64.Type}, {"telef", Int64.Type}, {"fax", Int64.Type}, {"mail", Int64.Type}, {"web", Int64.Type}, {"nat_jur", type text}, {"ncase", Int64.Type}, {"remu_m", type number}, {"gast_rem", type number}, {"gast_mat", type number}, {"gast_rac", type number}, {"gast_ee", type number}, {"gast_com", Int64.Type}, {"gast_ter", type number}, {"egresos", type number}, {"interes", type number}, {"tax", type number}, {"ingresos", type number}, {"otr_ing", type number}, {"ing_ext", Int64.Type}, {"financ", type text}, {"g_energ", type text}, {"kwh_a", type text}, {"tra_per", Int64.Type}, {"tra_ing", Int64.Type}, {"g_anocon", Int64.Type}, {"g_anoini", Int64.Type}, {"m_c_s", Int64.Type}}),
    #"Otras columnas quitadas" = Table.SelectColumns(#"Tipo cambiado",{"s6p2"}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Otras columnas quitadas",{{"s6p2", "id_s6p2"}}),
    #"Columna duplicada" = Table.DuplicateColumn(#"Columnas con nombre cambiado", "id_s6p2", "id_s6p2 - Copia"),
    #"Columnas quitadas" = Table.RemoveColumns(#"Columna duplicada",{"id_s6p2 - Copia"}),
    #"Duplicados quitados" = Table.Distinct(#"Columnas quitadas"),
    #"Filas filtradas" = Table.SelectRows(#"Duplicados quitados", each ([id_s6p2] <> "")),
    #"Columna duplicada1" = Table.DuplicateColumn(#"Filas filtradas", "id_s6p2", "id_s6p2 - Copia"),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columna duplicada1",{{"id_s6p2 - Copia", "forma_establecimiento"}}),
    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado1","10","Empresa de persona natural",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","1","Institución sin fines de lucro que sirve a los hogares",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","2","Institución o empresa privada no financiera",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","3","Empresa de control extranjero",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","4","Empresa pública",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","5","Instituciones financieras y de seguros regulados por la SBS",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5","6","Gobierno (central, seccional, ministerios, etc.)",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado6","7","Cooperativa de ahorro y crédito",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Valor reemplazado8" = Table.ReplaceValue(#"Valor reemplazado7","8","Cooperativa (producción, consumo y servicios)",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Valor reemplazado9" = Table.ReplaceValue(#"Valor reemplazado8","9","Asociación",Replacer.ReplaceText,{"forma_establecimiento"}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado9",{{"id_s6p2", Int64.Type}}),
    #"Filas ordenadas" = Table.Sort(#"Tipo cambiado1",{{"id_s6p2", Order.Ascending}}),
    #"Fila Insertada" = Table.InsertRows(#"Filas ordenadas",10 ,{ [id_s6p2 = 0, forma_establecimiento = "Desconocido"] }),
    #"Filas ordenadas1" = Table.Sort(#"Fila Insertada",{{"id_s6p2", Order.Ascending}})
in
    #"Filas ordenadas1"